[tools]
node = "24.14.0"
rust = "1.94.0"
go = "1.26.0"
bun = "1.3.10"
opencode = "1.2.16"
atuin = "18.13.3"
zoxide = "0.9.9"
starship = "1.24.2"
"aqua:charmbracelet/gum" = "0.17.0"
"aqua:charmbracelet/glow" = "2.1.1"
"aqua:charmbracelet/mods" = "1.8.1"
"aqua:topgrade-rs/topgrade" = "16.9.0"
"aqua:Nukesor/pueue/pueue" = "4.0.3"
"aqua:Nukesor/pueue/pueued" = "4.0.3"
