[tools]
opencode = "1.2.16"
atuin = "18.12.1"
zoxide = "0.9.9"
starship = "1.24.2"
"aqua:charmbracelet/gum" = "0.17.0"
"aqua:charmbracelet/glow" = "2.1.1"
"aqua:charmbracelet/mods" = "1.8.1"
topgrade = "16.9.0"
go = "1.26.0"
node = "24.14.0"
