[tools]
node = "latest"
rust = "latest"
go = "latest"
bun = "latest"
opencode = "latest"
atuin = "latest"
zoxide = "latest"
starship = "latest"
"aqua:charmbracelet/gum" = "latest"
"aqua:charmbracelet/glow" = "latest"
"aqua:charmbracelet/mods" = "latest"
"aqua:topgrade-rs/topgrade" = "latest"
"aqua:Nukesor/pueue/pueue" = "latest"
"aqua:Nukesor/pueue/pueued" = "latest"
