export const headers: string[] = [
  ["link", { rel: "icon", href: "/icon.png" }],
  ["link", { rel: "manifest", href: "/manifest.json" }],
  ["link", { rel: "alternate", href: "https://dotfiles.io", hreflang: "en" }],
  ["link", { rel: "stylesheet", href: "https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,700%7CRoboto+Mono&display=fallback" }],
  ["meta", { name: "theme-color", content: "#F0F" }],
  ["meta", { itemprop: "accessibilityAPI", content: "ARIA" }],
  ["meta", { itemprop: "accessibilityControl", content: "fullKeyboardControl" }],
  ["meta", { itemprop: "accessibilityControl", content: "fullMouseControl" }],
  ["meta", { itemprop: "accessibilityHazard", content: "noFlashingHazard" }],
  ["meta", { itemprop: "accessibilityHazard", content: "noMotionSimulationHazard" }],
  ["meta", { itemprop: "accessibilityHazard", content: "noSoundHazard" }],
  ["meta", { name: "apple-mobile-web-app-status-bar-style", content: "black" },],
  ["meta", { name: "apple-mobile-web-app-title", content: "Dotfiles v0.2.462" },],
  ["meta", { name: "application-name", content: "Dotfiles v0.2.462" }],
  ["meta", { name: "author", content: "Sebastien Rousseau" }],
  ["meta", { name: "format-detection", content: "telephone=no" },],
  ["meta", { name: "msapplication-tap-highlight", content: "no" },],
  ["meta", { name: "robots", content: "index, follow" }],
  ["meta", { name: "twitter:card", content: "The Dotfiles provides modular configuration files (aliases, functions and paths) built for speed, higher performance, with the aim of helping you have an easy and centralized way to configure your environment and applications." }],
  ["meta", { name: "twitter:creator", content: "@wwdseb" }],
  ["meta", { name: "twitter:description", content: "The Dotfiles provides modular configuration files (aliases, functions and paths) built for speed, higher performance, with the aim of helping you have an easy and centralized way to configure your environment and applications." }],
  ["meta", { name: "twitter:image", content: "https://github.com/sebastienrousseau/dotfiles/raw/master/assets/dotfiles.svg" }],
  ["meta", { name: "twitter:site", content: "@wwdseb" }],
  ["meta", { name: "twitter:title", content: "Dotfiles v0.2.462" }],
  ["meta", { name: "twitter:url", content: "https://dotfiles.io/" }],
  ["meta", { property: "og:description", content: "The Dotfiles provides modular configuration files (aliases, functions and paths) built for speed, higher performance, with the aim of helping you have an easy and centralized way to configure your environment and applications." }],
  ["meta", { property: "og:image", content: "https://github.com/sebastienrousseau/dotfiles/raw/master/assets/dotfiles.svg" }],
  ["meta", { property: "og:locale", content: "en_gb" }],
  ["meta", { property: "og:site_name", content: "Dotfiles" }],
  ["meta", { property: "og:title", content: "Dotfiles v0.2.462" }],
  ["meta", { property: "og:type", content: "website" }],
  ["meta", { property: "og:url", content: "https://dotfiles.io/" }],
];
