gui:
  showIcons: true
  showListFooter: false
  showCommandLog: false
  showFileTree: true
  showRandomTip: false
  nerdFontsVersion: "3"
  border: rounded
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#313244"
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitFgColor:
      - "#89b4fa"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  log:
    showGraph: always

os:
  editPreset: nvim

keybinding:
  universal:
    quit: q
    return: <escape>
