#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2015-2026 Sebastien Rousseau
# shellcheck disable=SC1090,SC1091,SC2034
# Auto-generated exercise test for dot_local/bin/executable_git-ai-commit.
# Slice 3 of #883: backfill coverage by running each managed script
# through safe-mode entry points (--help / no-arg / invalid flag).
# Edit-by-hand to add behavioral assertions; the auto-shell will leave
# this file alone if `# AUTO-GENERATED: false` appears in the first
# 10 lines.
#
# AUTO-GENERATED: true

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "$SCRIPT_DIR/../../.." && pwd)}"
source "$SCRIPT_DIR/../../framework/assertions.sh"
source "$SCRIPT_DIR/../../framework/coverage_helpers.sh"

SCRIPT_FILE="$REPO_ROOT/defaults/dot_local/bin/executable_git-ai-commit"

trap cov_teardown_sandbox EXIT
cov_setup_sandbox

test_start "script_exists"
assert_file_exists "$SCRIPT_FILE" "dot_local/bin/executable_git-ai-commit must exist"

test_start "script_valid_syntax"
if bash -n "$SCRIPT_FILE" 2>/dev/null; then
  ((TESTS_PASSED++)) || true
  printf '%b\n' "  ${GREEN}✓${NC} $CURRENT_TEST"
else
  ((TESTS_FAILED++)) || true
  printf '%b\n' "  ${RED}✗${NC} $CURRENT_TEST"
fi

test_start "git_ai_commit_deep_branches_execute"
commit_tmp="$DOTFILES_COV_TMPDIR/git-ai-commit-deep"
mkdir -p "$commit_tmp/bin" "$commit_tmp/work"
cat >"$commit_tmp/bin/git" <<'EOF_GIT'
#!/usr/bin/env bash
case "$*" in
  "diff --cached --quiet")
    [[ -n "${DOTFILES_FAKE_NO_STAGED:-}" ]] && exit 0
    exit 1
    ;;
  "diff --cached --stat")
    printf ' file.txt | 2 +-\n'
    ;;
  "diff --cached")
    printf 'diff --git a/file.txt b/file.txt\n+new\n-old\n'
    ;;
  commit*)
    printf 'commit:%s\n' "$*"
    ;;
  *)
    printf 'git:%s\n' "$*"
    ;;
esac
EOF_GIT
for provider in claude aider agy sgpt ollama; do
  cat >"$commit_tmp/bin/$provider" <<'EOF_PROVIDER'
#!/usr/bin/env bash
case "$(basename "$0")" in
  claude) cat >/dev/null; printf 'fix(test): claude message\n\n- generated by claude\n' ;;
  aider) printf 'noise\nfix(test): aider message\n' ;;
  agy) cat >/dev/null; printf 'fix(test): agy message\n' ;;
  sgpt) printf 'fix(test): sgpt message\n' ;;
  ollama) cat >/dev/null; printf 'fix(test): ollama message\n' ;;
esac
EOF_PROVIDER
  chmod +x "$commit_tmp/bin/$provider"
done
cat >"$commit_tmp/bin/editor" <<'EOF_EDITOR'
#!/usr/bin/env bash
printf 'fix(test): edited message\n' >"$1"
EOF_EDITOR
chmod +x "$commit_tmp/bin/git" "$commit_tmp/bin/editor"
(
  set +e
  export PATH="$commit_tmp/bin:$PATH"
  export EDITOR="$commit_tmp/bin/editor"
  cd "$commit_tmp/work" || exit 1
  bash "$SCRIPT_FILE" --help
  printf '\n' | GIT_AI_PROVIDER=claude bash "$SCRIPT_FILE"
  printf 'n\n' | bash "$SCRIPT_FILE" --provider aider
  printf 'Y\n' | bash "$SCRIPT_FILE" --provider agy --edit
  printf 'Y\n' | bash "$SCRIPT_FILE" --provider sgpt
  printf 'Y\n' | OLLAMA_MODEL=test-model bash "$SCRIPT_FILE" --provider ollama
  printf 'Y\n' | bash "$SCRIPT_FILE" --provider unknown
  printf 'Y\n' | DOTFILES_FAKE_NO_STAGED=1 bash "$SCRIPT_FILE" --provider claude
  bash "$SCRIPT_FILE" --bad
) >/dev/null || true
assert_file_exists "$commit_tmp/bin/git" \
  "git-ai-commit deep branches used sandbox git shim"

cov_exercise_script "$SCRIPT_FILE"
cov_exercise_functions_file "$SCRIPT_FILE"

echo "RESULTS:$TESTS_RUN:$TESTS_PASSED:$TESTS_FAILED"
