#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright (c) 2015-2026 Sebastien Rousseau
## `dot completion <bash|zsh|fish|nu>` — emit shell completion for `dot`,
## generated from the canonical _dot_help_specs registry in bin/dot. Using one
## source of truth keeps all four shells in sync (the previously hand-maintained
## fish/nushell lists drifted and referenced non-existent commands).
##
## Usage:
##   dot completion bash  >> ~/.bashrc.d/dot.bash
##   dot completion zsh   > "${fpath[1]}/_dot"
##   dot completion fish  > ~/.config/fish/completions/dot.fish
##   dot completion nu    >> ~/.config/nushell/completions.nu

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../../lib/dot/utils.sh
source "$SCRIPT_DIR/../../../lib/dot/utils.sh"

_completion_dot_cli() {
  local src
  src="$(resolve_source_dir)"
  printf '%s/bin/dot\n' "$src"
}

# Emit "name<TAB>description" for every top-level command (a _dot_help_specs
# field-2 entry with no space; entries containing a space are subcommands).
# Strip ": ' from descriptions so they can't break any shell's quoting.
_completion_commands() {
  local cli
  cli="$(_completion_dot_cli)"
  awk -F'|' '
    /_dot_help_specs\(\)/ { in_func = 1; next }
    in_func && /cat <<'\''EOF'\''/ { in_block = 1; next }
    in_block && /^EOF$/ { exit }
    in_block && NF >= 3 && $2 !~ / / {
      name = $2
      # Description = fields 3..NF-1 rejoined: registry descriptions can
      # contain "|" (e.g. "--ai|-A") and the last field is the hint.
      desc = $3
      for (i = 4; i < NF; i++) desc = desc "|" $i
      gsub(/^[ \t]+|[ \t]+$/, "", name)
      gsub(/^[ \t]+|[ \t]+$/, "", desc)
      gsub(/[":\047]/, "", desc)
      if (name != "") print name "\t" desc
    }
  ' "$cli"
}

# Emit "parent<TAB>child<TAB>description" for every subcommand (a field-2
# entry that contains a space, e.g. "theme list" -> parent=theme child=list).
_completion_subcommands() {
  local cli
  cli="$(_completion_dot_cli)"
  awk -F'|' '
    /_dot_help_specs\(\)/ { in_func = 1; next }
    in_func && /cat <<'\''EOF'\''/ { in_block = 1; next }
    in_block && /^EOF$/ { exit }
    in_block && NF >= 3 && $2 ~ / / {
      full = $2
      desc = $3
      for (i = 4; i < NF; i++) desc = desc "|" $i
      gsub(/^[ \t]+|[ \t]+$/, "", full)
      gsub(/^[ \t]+|[ \t]+$/, "", desc)
      gsub(/[":\047]/, "", desc)
      parent = full; sub(/ .*/, "", parent)
      child = full; sub(/^[^ ]+ /, "", child)
      if (parent != "" && child != "") print parent "\t" child "\t" desc
    }
  ' "$cli"
}

# The printf templates below are the *text of the generated script*;
# `$cur`, `$prev`, `$commands` must reach the output unexpanded.
# shellcheck disable=SC2016
gen_bash() {
  local names parent child desc
  names="$(_completion_commands | cut -f1 | tr '\n' ' ')"
  printf '# dot bash completion — generated by: dot completion bash\n'
  printf '# Source this file, or install it to a bash-completion completions dir.\n'
  printf '_dot_completions() {\n'
  printf '  local cur prev commands\n'
  printf '  COMPREPLY=()\n'
  printf '  cur="${COMP_WORDS[COMP_CWORD]}"\n'
  printf '  prev="${COMP_WORDS[COMP_CWORD - 1]}"\n'
  printf "  commands='%s'\n" "${names% }"
  printf '  case "$prev" in\n'
  printf '    dot)\n'
  printf '      COMPREPLY=($(compgen -W "$commands" -- "$cur"))\n'
  printf '      return 0\n'
  printf '      ;;\n'
  # One case arm per parent command that has subcommands.
  while IFS=$'\t' read -r parent child desc; do
    printf '%s\t%s\n' "$parent" "$child"
  done < <(_completion_subcommands) |
    awk -F'\t' '{ subs[$1] = subs[$1] (subs[$1] == "" ? "" : " ") $2 }
      END { for (p in subs) printf "%s\t%s\n", p, subs[p] }' |
    LC_ALL=C sort |
    while IFS=$'\t' read -r parent child; do
      printf '    %s)\n' "$parent"
      printf '      COMPREPLY=($(compgen -W "%s" -- "$cur"))\n' "$child"
      printf '      return 0\n'
      printf '      ;;\n'
    done
  printf '  esac\n'
  printf '  COMPREPLY=($(compgen -f -- "$cur"))\n'
  printf '}\n'
  printf 'complete -F _dot_completions dot\n'
}

gen_zsh() {
  local name desc
  printf '#compdef dot\n# generated by: dot completion zsh\n'
  printf '_dot() {\n  local -a commands\n  commands=(\n'
  while IFS=$'\t' read -r name desc; do
    printf "    '%s:%s'\n" "$name" "$desc"
  done < <(_completion_commands)
  printf '  )\n  _describe '\''command'\'' commands\n}\n_dot "$@"\n'
}

gen_fish() {
  local name desc
  printf '# dot fish completion — generated by: dot completion fish\n'
  printf 'complete -c dot -f\n'
  while IFS=$'\t' read -r name desc; do
    printf 'complete -c dot -n "__fish_use_subcommand" -a %s -d "%s"\n' "$name" "$desc"
  done < <(_completion_commands)
  local parent child
  while IFS=$'\t' read -r parent child desc; do
    printf 'complete -c dot -n "__fish_seen_subcommand_from %s" -a %s -d "%s"\n' \
      "$parent" "$child" "$desc"
  done < <(_completion_subcommands)
}

gen_nu() {
  local name desc
  printf '# dot nushell completion — generated by: dot completion nu\n'
  printf 'export extern dot [\n  command?: string@dot_commands\n  ...args: string\n]\n'
  printf 'def dot_commands [] {\n  [\n'
  while IFS=$'\t' read -r name desc; do
    printf '    { value: "%s", description: "%s" }\n' "$name" "$desc"
  done < <(_completion_commands)
  printf '  ]\n}\n'
}

usage() {
  cat <<'USAGE'
Usage: dot completion <bash|zsh|fish|nu>

Generate shell completion for `dot` from the canonical command registry.

  dot completion bash  >> ~/.bashrc.d/dot.bash
  dot completion zsh   > "${fpath[1]}/_dot"
  dot completion fish  > ~/.config/fish/completions/dot.fish
  dot completion nu    >> ~/.config/nushell/completions.nu
USAGE
}

# Dispatch: $1 is the command name ("completion"); $2 is the target shell.
case "${2:-}" in
  bash) gen_bash ;;
  zsh) gen_zsh ;;
  fish) gen_fish ;;
  nu | nushell) gen_nu ;;
  "" | -h | --help | help) usage ;;
  *)
    echo "dot completion: unknown shell '${2}' (want: bash|zsh|fish|nu)" >&2
    exit 1
    ;;
esac
