#!/usr/bin/env bash
# Copyright (c) 2015-2026 Dotfiles. All rights reserved.
set -euo pipefail

# install-lite.sh -- Minimal bootstrap for devcontainer / Codespaces
# Installs CLI essentials only; skips GUI apps, fonts, macOS tools, tmux plugins.
# Idempotent: safe to run multiple times.

# ---------- helpers --------------------------------------------------------- #

info() { printf '\033[1;34m[lite]\033[0m %s\n' "$*"; }

command_exists() { command -v "$1" >/dev/null 2>&1; }

apt_install() {
  local pkg="$1"
  if dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q 'install ok installed'; then
    info "$pkg is already installed"
  else
    info "Installing $pkg ..."
    sudo apt-get install -y "$pkg"
  fi
}

# ---------- prerequisites --------------------------------------------------- #

info "Updating apt package index ..."
sudo apt-get update -qq

apt_install curl
apt_install git

# ---------- CLI essentials -------------------------------------------------- #

# neovim
apt_install neovim

# fzf
apt_install fzf

# ripgrep
apt_install ripgrep

# fd-find
apt_install fd-find

# bat
apt_install bat

# zoxide and starship: pinned release archives, verified against the
# SHA-256 values in versions.env by the provisioner's own installers (no
# remote install scripts run). Each runs in a subshell so a failed check
# warns instead of ending the bootstrap.
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=../install/lib/logging.sh
. "$REPO_DIR/install/lib/logging.sh"
# shellcheck source=../install/lib/installers.sh
. "$REPO_DIR/install/lib/installers.sh"
# shellcheck source=../defaults/dot_config/dotfiles/versions.env
. "$REPO_DIR/defaults/dot_config/dotfiles/versions.env"
lite_arch="$(resolve_arch)"

if command_exists zoxide; then
  info "zoxide is already installed"
else
  info "Installing zoxide ..."
  (install_from_tarball \
    "https://github.com/ajeetdsouza/zoxide/releases/download/v${ZOXIDE_TAG#v}/zoxide-${ZOXIDE_TAG#v}-${lite_arch}-unknown-linux-musl.tar.gz" \
    "" zoxide "$HOME/.local/bin" "$(pinned_sha256 ZOXIDE)") ||
    info "Warning: zoxide failed verification or download, skipping"
fi

# eza: apt's signed-by trusts every primary key in the keyring, so it must
# hold exactly the pinned one. Fingerprint read from
# https://raw.githubusercontent.com/eza-community/eza/main/deb.asc on 2026-10-08.
EZA_GPG_FPR="1548BC8A4B4D2688F9B0DAF7EC29E2090CE3FD43"
if command_exists eza; then
  info "eza is already installed"
else
  info "Installing eza ..."
  sudo mkdir -p /etc/apt/keyrings
  if [[ ! -f /etc/apt/keyrings/gierens.gpg ]]; then
    curl --proto '=https' --tlsv1.2 -fsSL https://raw.githubusercontent.com/eza-community/eza/main/deb.asc |
      sudo gpg --batch --dearmor -o /etc/apt/keyrings/gierens.gpg
  fi
  if apt_keyring_holds_only /etc/apt/keyrings/gierens.gpg "$EZA_GPG_FPR"; then
    if [[ ! -f /etc/apt/sources.list.d/gierens.list ]]; then # mutation: ignore devcontainer-only apt setup, needs root and apt
      echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] https://deb.gierens.de stable main" |
        sudo tee /etc/apt/sources.list.d/gierens.list >/dev/null
      sudo apt-get update -qq
    fi
    sudo apt-get install -y eza
  else
    sudo rm -f /etc/apt/keyrings/gierens.gpg
    info "Warning: eza signing key is not the pinned $EZA_GPG_FPR, skipping"
  fi
fi

if command_exists starship; then
  info "starship is already installed"
else
  info "Installing starship ..."
  (install_from_tarball \
    "https://github.com/starship/starship/releases/download/${STARSHIP_TAG}/starship-${lite_arch}-unknown-linux-musl.tar.gz" \
    "https://github.com/starship/starship/releases/download/${STARSHIP_TAG}/starship-${lite_arch}-unknown-linux-musl.tar.gz.sha256" \
    starship "$HOME/.local/bin" "$(pinned_sha256 STARSHIP)") ||
    info "Warning: starship failed verification or download, skipping"
fi

# ---------- minimal zshrc --------------------------------------------------- #

ZSHRC_TARGET="${HOME}/.zshrc"

if [[ ! -f "$ZSHRC_TARGET" ]] || ! grep -q 'install-lite' "$ZSHRC_TARGET" 2>/dev/null; then
  info "Writing minimal .zshrc ..."
  cat >"$ZSHRC_TARGET" <<'ZSHRC'
# Minimal zshrc -- generated by .devcontainer/install-lite.sh
# Sources only core shell configs for a lightweight container experience.

export DOTFILES_CONTAINER=1

# XDG base directories
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

# PATH essentials
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

# Source core shell configs if they exist
for cfg in "$XDG_CONFIG_HOME"/shell/00-*.sh "$XDG_CONFIG_HOME"/shell/05-*.sh "$XDG_CONFIG_HOME"/shell/90-*.sh; do
  [ -f "$cfg" ] && source "$cfg"
done

# fd-find is packaged as fdfind on Debian/Ubuntu
if command -v fdfind >/dev/null 2>&1 && ! command -v fd >/dev/null 2>&1; then
  alias fd='fdfind'
fi

# bat is packaged as batcat on Debian/Ubuntu
if command -v batcat >/dev/null 2>&1 && ! command -v bat >/dev/null 2>&1; then
  alias bat='batcat'
fi

# Initialise zoxide
if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi

# Initialise starship
if command -v starship >/dev/null 2>&1; then
  eval "$(starship init zsh)"
fi
ZSHRC
fi

info "Lite bootstrap complete."
