#!/usr/bin/env bash
set -euo pipefail

# install-lite.sh -- Minimal bootstrap for devcontainer / Codespaces
# Installs CLI essentials only; skips GUI apps, fonts, macOS tools, tmux plugins.
# Idempotent: safe to run multiple times.

# ---------- helpers --------------------------------------------------------- #

info() { printf '\033[1;34m[lite]\033[0m %s\n' "$*"; }

command_exists() { command -v "$1" >/dev/null 2>&1; }

apt_install() {
  local pkg="$1"
  if dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q 'install ok installed'; then
    info "$pkg is already installed"
  else
    info "Installing $pkg ..."
    sudo apt-get install -y "$pkg"
  fi
}

# ---------- prerequisites --------------------------------------------------- #

info "Updating apt package index ..."
sudo apt-get update -qq

apt_install curl
apt_install git

# ---------- CLI essentials -------------------------------------------------- #

# neovim
apt_install neovim

# fzf
apt_install fzf

# ripgrep
apt_install ripgrep

# fd-find
apt_install fd-find

# bat
apt_install bat

# zoxide
# SECURITY NOTE: curl|sh is used for devcontainer convenience only.
# Production installs should use the system package manager or a pinned binary.
if command_exists zoxide; then
  info "zoxide is already installed"
else
  info "Installing zoxide ..."
  curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
fi

# eza
if command_exists eza; then
  info "eza is already installed"
else
  info "Installing eza ..."
  sudo mkdir -p /etc/apt/keyrings
  if [ ! -f /etc/apt/keyrings/gierens.gpg ]; then
    wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc \
      | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
  fi
  if [ ! -f /etc/apt/sources.list.d/gierens.list ]; then
    echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" \
      | sudo tee /etc/apt/sources.list.d/gierens.list >/dev/null
    sudo apt-get update -qq
  fi
  sudo apt-get install -y eza
fi

# starship prompt
# SECURITY NOTE: curl|sh is used for devcontainer convenience only.
# Production installs should use the system package manager or a pinned binary.
if command_exists starship; then
  info "starship is already installed"
else
  info "Installing starship ..."
  curl -sSfL https://starship.rs/install.sh | sh -s -- --yes
fi

# ---------- minimal zshrc --------------------------------------------------- #

ZSHRC_TARGET="${HOME}/.zshrc"

if [ ! -f "$ZSHRC_TARGET" ] || ! grep -q 'install-lite' "$ZSHRC_TARGET" 2>/dev/null; then
  info "Writing minimal .zshrc ..."
  cat > "$ZSHRC_TARGET" << 'ZSHRC'
# Minimal zshrc -- generated by .devcontainer/install-lite.sh
# Sources only core shell configs for a lightweight container experience.

export DOTFILES_CONTAINER=1

# XDG base directories
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

# PATH essentials
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

# Source core shell configs if they exist
for cfg in "$XDG_CONFIG_HOME"/shell/00-*.sh "$XDG_CONFIG_HOME"/shell/05-*.sh "$XDG_CONFIG_HOME"/shell/90-*.sh; do
  [ -f "$cfg" ] && source "$cfg"
done

# fd-find is packaged as fdfind on Debian/Ubuntu
if command -v fdfind >/dev/null 2>&1 && ! command -v fd >/dev/null 2>&1; then
  alias fd='fdfind'
fi

# bat is packaged as batcat on Debian/Ubuntu
if command -v batcat >/dev/null 2>&1 && ! command -v bat >/dev/null 2>&1; then
  alias bat='batcat'
fi

# Initialise zoxide
if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi

# Initialise starship
if command -v starship >/dev/null 2>&1; then
  eval "$(starship init zsh)"
fi
ZSHRC
fi

info "Lite bootstrap complete."
