#!/usr/bin/env bash
# Copyright (c) 2015-2026 Dotfiles. All rights reserved.
# Example: Complete dot command reference — one usage line per public
# command/subcommand. Generated from bin/dot (_dot_help_specs) and kept
# in sync by the per-command contract in scripts/qa/examples-coverage.sh.
set -euo pipefail

printf 'dot — declarative dotfiles CLI. Public commands:\n\n'

printf '\n[Core]\n'
printf '  dot sync — Apply dotfiles (alias for apply; --pull to fetch, --check to preview)\n'
printf '  dot add — Add a file to chezmoi source\n'
printf '  dot diff — Show chezmoi diff with exclusions\n'
printf '  dot status — Show configuration drift (chezmoi status)\n'
printf '  dot edit — Open chezmoi source in $EDITOR\n'
printf '  dot cd — Print source directory path (use: cd $(dot cd))\n'
printf '  dot commit — AI-powered conventional commit\n'
printf '\n[Diagnostics]\n'
printf '  dot doctor — Deep audit: tools, paths, portability, AI analysis (--ai\n'
printf '  dot attest — Export workstation attestation evidence (--json\n'
printf '  dot score — System health and security scorecard\n'
printf '  dot snapshot — Capture baseline system snapshot\n'
printf '  dot chaos — Simulate config corruption to test self-healing\n'
printf '  dot bundle — Create offline archive of dotfiles environment\n'
printf '  dot rollback — Rollback dotfiles to a previous state\n'
printf '  dot history — Shell history analysis\n'
printf '  dot perf — Show performance mode and quick timing\n'
printf '  dot metrics — Show recent observability metrics (JSONL)\n'
printf '  dot load-bench — Measure time to heavy-layer readiness\n'
printf '\n[AI]\n'
printf '  dot ai — AI fleet cockpit, gateway, and cost\n'
printf '  dot ai-setup — Interactive setup for all AI CLI tools\n'
printf '  dot ai-query — Context-aware RAG query over your dotfiles\n'
printf '  dot mcp — Inspect MCP policy, supply chain, and registry\n'
printf '  dot mode — Set or inspect agent operating profiles (ask/plan/apply/audit)\n'
printf '  dot agent — Profile-aware execution, agent card, a2a-card, session log, checkpoints, and conformance\n'
printf '  dot cl — Claude CLI with context patterns\n'
printf '  dot copilot — GitHub Copilot CLI with context patterns\n'
printf '  dot agy — Antigravity CLI with context patterns\n'
printf '  dot kiro — Kiro CLI with context patterns\n'
printf '  dot sgpt — Shell-GPT with context patterns\n'
printf '  dot ollama — Ollama with context patterns\n'
printf '  dot opencode — OpenCode with context patterns\n'
printf '  dot aider — Aider with context patterns\n'
printf '\n[Tools]\n'
printf '  dot env — Tool versions (mise)\n'
printf '  dot profile — Show/switch configuration profile\n'
printf '  dot keys — Keybindings (sign-check: verify git signing)\n'
printf '  dot tools — Show or install nix packages\n'
printf '  dot new — Create a new project from a template\n'
printf '  dot sandbox — Launch a safe sandbox preview (Docker/Podman)\n'
printf '  dot lint — Lint shell scripts (--fix\n'
printf '  dot learn — Start the interactive tour of your new tools\n'
printf '  dot docs — Show repo README\n'
printf '\n[Appearance]\n'
printf '  dot theme — Switch terminal theme (dark/light)\n'
printf '  dot wallpaper — Apply a wallpaper from your library [macOS,Linux]\n'
printf '  dot fonts — Install Nerd Fonts (JetBrainsMono by default)\n'
printf '  dot tune — Apply OS tuning (opt-in) [macOS,Linux]\n'
printf '\n[Secrets]\n'
printf '  dot secrets-init — Initialize age key for secrets\n'
printf '  dot secrets — Edit encrypted secrets (age)\n'
printf '  dot secrets-create — Create an encrypted secrets file\n'
printf '  dot ssh-key — Encrypt an SSH key locally with age\n'
printf '  dot ssh-cert — Manage short-lived SSH certificates\n'
printf '\n[Security (opt-in)]\n'
printf '  dot backup — Create a compressed backup of your home\n'
printf '  dot encrypt-check — Check disk encryption status\n'
printf '  dot firewall — Apply firewall hardening [macOS,Linux]\n'
printf '  dot telemetry — Disable OS telemetry [macOS,Linux]\n'
printf '  dot dns-doh — Enable DNS-over-HTTPS [macOS,Linux]\n'
printf '  dot lock-screen — Enforce lock screen idle settings [Linux]\n'
printf '  dot usb-safety — Disable automount for removable media [Linux]\n'
printf '\n[Fleet]\n'
printf '  dot fleet — Show fleet node status, drift, and namespace (--json for machine output)\n'
printf '  dot fleet drift — Check for configuration drift across managed files\n'
printf '  dot fleet namespace — Show or set the active namespace for multi-tenant isolation\n'
printf '  dot fleet events — Show recent fleet events from local event log\n'
printf '\n[Meta]\n'
printf '  dot upgrade — Update system toolchains, plugins, and dotfiles\n'
printf '  dot packages — List installed packages and package managers\n'
printf '  dot cache-refresh — Regenerate shell caches for ultra-fast startup\n'
printf '  dot search — Find commands by keyword\n'
printf '  dot version — Show version information.\n'
printf '  dot help — Show this help message\n'
printf '\n[Fleet]\n'
printf '  dot fleet status — Show this nodes fleet status: id, namespace, version, OS, drift, last apply\n'
printf '  dot fleet enforce — Show or set RBAC enforcement mode (advisory/strict) for agent profiles\n'
printf '  dot fleet apply — SSH to every host in fleet.toml and run dot sync (or a custom --cmd)\n'
printf '\n[AI]\n'
printf '  dot ai chat — Start an interactive AI session with a chosen tool\n'
printf '  dot ai tools — Show installed AI CLI tools and their versions\n'
printf '  dot ai install — Install AI CLI tools via mise/native installers\n'
printf '  dot ai serve — Run the local AI gateway/proxy that routes non-Claude providers\n'
printf '  dot ai cost — Report AI spend across every provider from the unified run log\n'
printf '  dot ai login — Interactive setup/authentication for installed AI CLI tools\n'
printf '  dot ai doctor — Diagnose AI tooling configuration and connectivity\n'
printf '  dot ai ask — Context-aware RAG query over your dotfiles\n'
printf '  dot ai run — Run a one-shot prompt with an AI tool\n'
printf '  dot ai delegate — Delegate a coding task to a cheaper AI model under agent policy\n'
printf '  dot mode list — List available agent operating profiles (ask/plan/apply/audit)\n'
printf '  dot mode current — Show the active agent profile and its policy\n'
printf '  dot mode show — Show details of a specific agent profile\n'
printf '  dot mode set — Switch the active agent profile\n'
printf '  dot mode run — Run a command under a given agent profile with a checkpoint\n'
printf '  dot mode doctor — Validate the agent-profiles.json config and default profile\n'
printf '  dot agent card — Show the local agent card metadata\n'
printf '  dot agent log — Tail the agent session audit log\n'
printf '  dot agent checkpoint — Manage agent run checkpoints (save/list/show/replay)\n'
printf '  dot agent delegate — Delegate execution to an allowed sub-agent\n'
printf '  dot agent a2a-card — Show or validate the A2A v0.3 agent card\n'
printf '  dot agent conformance — Run the A2A conformance test suite\n'
printf '  dot mcp doctor — Run the MCP policy/supply-chain/config audit\n'
printf '  dot mcp registry — Show the configured MCP server registry\n'
printf '\n[Secrets]\n'
printf '  dot secrets edit — Edit the encrypted secrets file (age)\n'
printf '  dot secrets set — Store a secret value under a key\n'
printf '  dot secrets get — Retrieve a secret value (--raw for plaintext)\n'
printf '  dot secrets list — List indexed secret keys\n'
printf '  dot secrets load — Emit export lines for a secrets bucket (use with eval)\n'
printf '  dot secrets provider — Show the active secrets provider\n'
printf '\n[Tools]\n'
printf '  dot env list — List managed tool versions via mise\n'
printf '  dot env prune — Show or remove orphan tool installs (--yes to commit)\n'
printf '  dot env install — Install requested tool versions via mise\n'
printf '  dot env use — Pin a tool version globally/locally via mise\n'
printf '  dot registry list — List modules in the configured module registry\n'
printf '  dot registry search — Filter registry modules by keyword\n'
printf '  dot registry info — Print full metadata for a registry module\n'
printf '  dot registry install — Install a registry module (scaffold)\n'
printf '  dot registry url — Show the active registry URL\n'
printf '  dot registry set-url — Override the registry URL (https only; persists)\n'
printf '\n[Appearance]\n'
printf '  dot theme list — Show all available terminal/wallpaper themes\n'
printf '  dot theme set — Set a theme by name (interactive picker if omitted)\n'
printf '  dot theme toggle — Toggle light/dark within the current theme family\n'
printf '  dot theme sync — Sync the dotfiles theme with system dark/light mode\n'
printf '  dot theme family — Cycle between theme families\n'
printf '  dot theme current — Show the current theme info\n'
printf '  dot theme rebuild — Regenerate themes from system and custom wallpapers\n'
printf '  dot wallpaper sync — Sync wallpaper from your library\n'
printf '  dot wallpaper rotate — Rotate to the next wallpaper in your library\n'
printf '\n[Tools]\n'
printf '  dot tools install — Enter the Nix development shell with all managed tools\n'
printf '  dot tools docs — Show the full tools markdown documentation\n'
printf '  dot profile show — Show the active configuration profile and feature flags\n'
printf '  dot profile set — Set the active configuration profile (run dot sync to apply)\n'
printf '\n[AI]\n'
printf '  dot agents list — Show recognised AI agent harnesses and their config paths\n'
printf '  dot agents check — Verify AGENTS.md tracks CLAUDE.md (exit 1 if drifted)\n'
printf '  dot agents render — Regenerate AGENTS.md and per-harness config from CLAUDE.md\n'
printf '\n[Tools]\n'
printf '  dot aliases list — List all shell aliases shipped by the dotfiles\n'
printf '  dot aliases search — Search aliases by term\n'
printf '  dot aliases why — Show details and deprecation status for a single alias\n'
printf '  dot aliases stats — Show alias usage counts from shell history\n'
printf '  dot aliases cheatsheet — Generate the alias cheatsheet markdown\n'
printf '  dot aliases tiers — Show which alias tiers/ecosystems are enabled\n'
printf '\n[AI]\n'
printf '  dot patterns list — List AI steering patterns\n'
printf '  dot patterns view — View an AI steering pattern\n'
printf '  dot patterns edit — Edit an AI steering pattern in $EDITOR\n'
printf '\n[Tools]\n'
printf '  dot keys sign-check — Verify git commit-signing configuration and key availability\n'

printf '\nCommand reference example complete.\n'
