#!/usr/bin/env bash
# Copyright (c) 2015-2026 Dotfiles. All rights reserved.
# Example: Complete dot command reference — one usage line per public
# command/subcommand. Generated from bin/dot (_dot_help_specs) and kept
# in sync by the per-command contract in scripts/qa/examples-coverage.sh.
set -euo pipefail

printf 'dot — declarative dotfiles CLI. Public commands:\n\n'

printf '\n[Core]\n'
printf '  dot sync — Apply dotfiles (alias for apply; --pull to fetch, --check to preview)\n'
printf '  dot add — Add a file to chezmoi source\n'
printf '  dot diff — Show chezmoi diff with exclusions\n'
printf '  dot status — Show configuration drift (chezmoi status)\n'
printf '  dot edit — Open chezmoi source in $EDITOR\n'
printf '  dot cd — Print source directory path (use: cd $(dot cd))\n'
printf '  dot commit — AI-powered conventional commit\n'
printf '\n[Diagnostics]\n'
printf '  dot doctor — Deep audit: tools, paths, portability, AI analysis (--ai\n'
printf '  dot attest — Export workstation attestation evidence (--json\n'
printf '  dot score — System health and security scorecard\n'
printf '  dot snapshot — Capture baseline system snapshot\n'
printf '  dot chaos — Simulate config corruption to test self-healing\n'
printf '  dot bundle — Create offline archive of dotfiles environment\n'
printf '  dot rollback — Rollback dotfiles to a previous state\n'
printf '  dot history — Shell history analysis\n'
printf '  dot perf — Show performance mode and quick timing\n'
printf '  dot metrics — Show recent observability metrics (JSONL)\n'
printf '  dot load-bench — Measure time to heavy-layer readiness\n'
printf '\n[AI]\n'
printf '  dot ai — AI fleet cockpit, gateway, and cost\n'
printf '  dot ai-setup — Interactive setup for all AI CLI tools\n'
printf '  dot ai-query — Context-aware RAG query over your dotfiles\n'
printf '  dot mcp — Inspect MCP policy, supply chain, and registry\n'
printf '  dot mode — Set or inspect agent operating profiles (ask/plan/apply/audit)\n'
printf '  dot agent — Profile-aware execution, agent card, a2a-card, session log, checkpoints, and conformance\n'
printf '  dot cl — Claude CLI with context patterns\n'
printf '  dot copilot — GitHub Copilot CLI with context patterns\n'
printf '  dot agy — Antigravity CLI with context patterns\n'
printf '  dot kiro — Kiro CLI with context patterns\n'
printf '  dot sgpt — Shell-GPT with context patterns\n'
printf '  dot ollama — Ollama with context patterns\n'
printf '  dot opencode — OpenCode with context patterns\n'
printf '  dot aider — Aider with context patterns\n'
printf '\n[Tools]\n'
printf '  dot env — Tool versions (mise)\n'
printf '  dot profile — Show/switch configuration profile\n'
printf '  dot keys — Keybindings (sign-check: verify git signing)\n'
printf '  dot tools — Show or install nix packages\n'
printf '  dot new — Create a new project from a template\n'
printf '  dot sandbox — Launch a safe sandbox preview (Docker/Podman)\n'
printf '  dot lint — Lint shell scripts (--fix\n'
printf '  dot learn — Start the interactive tour of your new tools\n'
printf '  dot docs — Show repo README\n'
printf '\n[Appearance]\n'
printf '  dot theme — Switch terminal theme (dark/light)\n'
printf '  dot wallpaper — Apply a wallpaper from your library [macOS,Linux]\n'
printf '  dot fonts — Install Nerd Fonts (JetBrainsMono by default)\n'
printf '  dot tune — Apply OS tuning (opt-in) [macOS,Linux]\n'
printf '\n[Secrets]\n'
printf '  dot secrets-init — Initialize age key for secrets\n'
printf '  dot secrets — Edit encrypted secrets (age)\n'
printf '  dot secrets-create — Create an encrypted secrets file\n'
printf '  dot ssh-key — Encrypt an SSH key locally with age\n'
printf '  dot ssh-cert — Manage short-lived SSH certificates\n'
printf '\n[Security (opt-in)]\n'
printf '  dot backup — Create a compressed backup of your home\n'
printf '  dot encrypt-check — Check disk encryption status\n'
printf '  dot firewall — Apply firewall hardening [macOS,Linux]\n'
printf '  dot telemetry — Disable OS telemetry [macOS,Linux]\n'
printf '  dot dns-doh — Enable DNS-over-HTTPS [macOS,Linux]\n'
printf '  dot lock-screen — Enforce lock screen idle settings [Linux]\n'
printf '  dot usb-safety — Disable automount for removable media [Linux]\n'
printf '\n[Fleet]\n'
printf '  dot fleet — Show fleet node status, drift, and namespace (--json for machine output)\n'
printf '  dot fleet drift — Check for configuration drift across managed files\n'
printf '  dot fleet namespace — Show or set the active namespace for multi-tenant isolation\n'
printf '  dot fleet events — Show recent fleet events from local event log\n'
printf '\n[Meta]\n'
printf '  dot upgrade — Update system toolchains, plugins, and dotfiles\n'
printf '  dot packages — List installed packages and package managers\n'
printf '  dot cache-refresh — Regenerate shell caches for ultra-fast startup\n'
printf '  dot search — Find commands by keyword\n'
printf '  dot version — Show version information.\n'
printf '  dot help — Show this help message\n'

printf '\nCommand reference example complete.\n'
