# Wayland session environment variables
ELECTRON_OZONE_PLATFORM_HINT=auto
TERMINAL=ghostty

# Qt Wayland support
QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME=gtk3

# Firefox native Wayland
MOZ_ENABLE_WAYLAND=1

# SDL Wayland support
SDL_VIDEODRIVER=wayland

# Java AWT fix (JetBrains IDEs, Ghidra)
_JAVA_AWT_WM_NONREPARENTING=1

# DMS icon theme
QS_ICON_THEME=Papirus-Dark
