export const head: string[] = [
  ["link", { rel: "icon", href: "/icon.png" }],
  ["link", { rel: "manifest", href: "/manifest.json" }],
  ["link", { rel: "alternate", href: "https://skeletonic.io", hreflang: "en" }],
  ["link", { rel: "stylesheet", href: "https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,700%7CRoboto+Mono&display=fallback" }],
  ["meta", { name: "theme-color", content: "#F0F" }],
  ["meta", { itemprop: "accessibilityAPI", content: "ARIA" }],
  ["meta", { itemprop: "accessibilityControl", content: "fullKeyboardControl" }],
  ["meta", { itemprop: "accessibilityControl", content: "fullMouseControl" }],
  ["meta", { itemprop: "accessibilityHazard", content: "noFlashingHazard" }],
  ["meta", { itemprop: "accessibilityHazard", content: "noMotionSimulationHazard" }],
  ["meta", { itemprop: "accessibilityHazard", content: "noSoundHazard" }],
  ["meta", { name: "apple-mobile-web-app-status-bar-style", content: "black" },],
  ["meta", { name: "apple-mobile-web-app-title", content: "Dotfiles" },],
  ["meta", { name: "application-name", content: "Dotfiles" }],
  ["meta", { name: "author", content: "Sebastien Rousseau" }],
  ["meta", { name: "format-detection", content: "telephone=no" },],
  ["meta", { name: "msapplication-tap-highlight", content: "no" },],
  ["meta", { name: "robots", content: "index, follow" }],
  ["meta", { name: "twitter:alt", content: "Starship: Cross-Shell Prompt" }],
  ["meta", { name: "twitter:card", content: "Dotfiles is a lightweight, intuitive, accessible and ultra-responsive cascading style sheets framework to streamline your Digital and Mobile Web development needs." }],
  ["meta", { name: "twitter:creator", content: "@wwdseb" }],
  ["meta", { name: "twitter:description", content: "Dotfiles is a lightweight, intuitive, accessible and ultra-responsive cascading style sheets framework to streamline your Digital and Mobile Web development needs." }],
  ["meta", { name: "twitter:image", content: "https://dotfiles.io/assets/images/backgrounds/background-skeletonic.min.svg" }],
  ["meta", { name: "twitter:site", content: "@skeletonic" }],
  ["meta", { name: "twitter:title", content: "Dotfiles" }],
  ["meta", { name: "twitter:url", content: "https://dotfiles.io/" }],
  ["meta", { property: "og:description", content: "Dotfiles is a lightweight, intuitive, accessible and ultra-responsive cascading style sheets framework to streamline your Digital and Mobile Web development needs." }],
  ["meta", { property: "og:image", content: "https://dotfiles.io/assets/images/backgrounds/background-skeletonic.min.svg" }],
  ["meta", { property: "og:locale", content: "en_gb" }],
  ["meta", { property: "og:site_name", content: "Dotfiles" }],
  ["meta", { property: "og:title", content: "Dotfiles" }],
  ["meta", { property: "og:type", content: "website" }],
  ["meta", { property: "og:url", content: "https://dotfiles.io/" }],
];