#!/usr/bin/env bash
# Copyright (c) 2015-2026 Dotfiles. All rights reserved.
# shellcheck disable=SC1090,SC1091,SC2034
# Snapshot tests for the `dot` CLI output surface.
#
# Each .snap file in this directory was generated by `update.sh` and
# is expected to match the current output of `dot <cmd>` after the
# same scrubbing is applied. When a test fails, decide:
#   (a) the change to the CLI was intentional — run `update.sh` and
#       commit the new snapshots, or
#   (b) the change is a regression — fix the CLI to restore the
#       previous output.
#
# Regression for: GH-881
# Why: prevent silent breaking changes to user-facing CLI output that
# downstream scripts / screenshots / asciinema recordings depend on.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
# shellcheck source=../framework/assertions.sh
source "$REPO_ROOT/tests/framework/assertions.sh"

DOT_BIN="$REPO_ROOT/dot_local/bin/executable_dot"
SCRUB="$SCRIPT_DIR/scrub.sh"

check_snapshot() {
  local slug="$1" ; shift
  local expected="$SCRIPT_DIR/${slug}.snap"

  test_start "snapshot_${slug}"

  if [[ ! -f "$expected" ]]; then
    assert_exit_code 0 "false  # missing snapshot file: $expected"
    return
  fi

  local actual
  actual=$(DOTFILES_NONINTERACTIVE=1 NO_COLOR=1 bash "$DOT_BIN" "$@" 2>&1 | bash "$SCRUB" || true)
  local snapshot
  snapshot=$(cat "$expected")

  if [[ "$actual" == "$snapshot" ]]; then
    assert_exit_code 0 "true"
  else
    # Surface the diff inline for fast triage.
    {
      printf '\n--- diff: actual vs %s ---\n' "$expected"
      diff <(printf '%s' "$snapshot") <(printf '%s' "$actual") | head -40
      printf -- '--- end diff ---\n\n'
    } >&2
    assert_exit_code 0 "false  # snapshot drift — run tests/snapshots/update.sh and review"
  fi
}

test_start "scrub_script_executable"
if [[ -x "$SCRUB" ]]; then
  assert_exit_code 0 "true"
else
  assert_exit_code 0 "false  # scrub.sh must be executable"
fi

check_snapshot help    --help
check_snapshot version version
check_snapshot doctor  doctor
check_snapshot perf    perf
check_snapshot health  health

echo "RESULTS:$TESTS_RUN:$TESTS_PASSED:$TESTS_FAILED"
