name: "Coveralls"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - run: echo ${{github.ref}}

      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
            version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: Lint fix
      #   run: pnpm run lint:fix

      # - name: Run prettier
      #   run: pnpm run format

      # - name: Run remark
      #   run: pnpm run lint:markdown

      - name: Build
        run: pnpm run build

      # - name: Testing & Coverage
      #   run: pnpm run test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          base-path: /
          flag-name: pm2md
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: ./coverage/lcov.info
