name: Dotfiles Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/main' }}
        name: Configure npm token
        run: pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - name: Publish Dry Run
        run: pnpm -r publish --no-git-checks --dry-run
      - if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/main' }}
        name: Publish if needed
        run: pnpm -r publish --access public
